repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: double-quote-string-fixer
# 由於 requirements.txt 有自己的排版方式，本專案不使用此formatter
#    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.0
    hooks:
    -   id: seed-isort-config
# 參數帶入方式
#        args: [--settings-path=., --application-directories=.]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.27.0'
    hooks:
    -   id: yapf
